#!/bin/bash
#ddev-generated

## Description: Ejecución de análisis de código (GrumPHP).
## Usage: grumphp
## Example: ddev grumphp

# ##############################################################################
# VARIABLES AUXILIARES.
# ##############################################################################

# Colores.
RESET="\033[0m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
GREEN="\033[0;32m"

################################################################################
# FUNCIONES AUXILIARES.
################################################################################

# Simplemente imprime una línea por pantalla.
function linea() {
  echo '--------------------------------------------------------------------------------'
}

################################################################################
# COMPROBACIONES PREVIAS.
################################################################################

if [ ! -f /var/www/html/vendor/bin/grumphp ]; then
  clear
  echo " "
  linea
  echo -e " ${RED}Error: GrumPHP no está instalado.${RESET}"
  echo -e " ${YELLOW}Ejecuta: ddev composer require --dev phpro/grumphp-shim${RESET}"
  linea
  echo " "
  exit 1
fi

################################################################################
# CUERPO PRINCIPAL DEL SCRIPT.
################################################################################

/var/www/html/vendor/bin/grumphp run
