#!/bin/bash
#ddev-generated

## Description: Revisar enlaces rotos en el sitio.
## Usage: linkchecker
## Example: ddev linkchecker

linkchecker \
  --no-status \
  --no-warnings \
  --check-extern \
  --timeout=10 \
  --threads=30 \
  --file-output=reporte-${DDEV_SITENAME}.html \
  --ignore-url="^mailto:" \
  --ignore-url=".*\.(css|js)$" \
  --user-agent="Mozilla/5.0 (compatible; linkchecker)" \
  https://${DDEV_HOSTNAME}
