#!/bin/bash
#ddev-generated

## Description: Ejecución PHPUnit pasando la suite que queremos ejecutar.
## Usage: phpunit [suite]
## Example: ddev phpunit unit

set -eu -o pipefail

# ##############################################################################
# VARIABLES AUXILIARES.
# ##############################################################################

# Colores.
RESET="\033[0m"
YELLOW="\033[0;33m"
RED="\033[0;31m"

################################################################################
# FUNCIONES AUXILIARES.
################################################################################

# Simplemente imprime una línea por pantalla.
function linea() {
  echo '--------------------------------------------------------------------------------'
}

################################################################################
# COMPROBACIONES PREVIAS.
################################################################################

if [ ! -f /var/www/html/vendor/bin/phpunit ]; then
  clear
  echo " "
  linea
  echo -e " ${RED}Error: PHPUnit no está instalado.${RESET}"
  echo -e " ${YELLOW}Ejecuta: ddev composer require --dev phpunit/phpunit${RESET}"
  linea
  echo " "
  exit 1
fi

################################################################################
# CUERPO PRINCIPAL DEL SCRIPT.
################################################################################

# CHECK for local config.
if [ -f "phpunit.xml" ]; then
  # Defer to local config
  phpunit "$@"
else
  # Check if we are running a specific test or test folder.
  if [ $# -gt 0 ] && [ -e "$1" ]; then
    TEST_PATH="$1"
    shift
    phpunit --bootstrap $PWD/$DDEV_DOCROOT/core/tests/bootstrap.php "$TEST_PATH" "$@"
  else
    # Run all custom module tests.
    phpunit --bootstrap $PWD/$DDEV_DOCROOT/core/tests/bootstrap.php $DDEV_DOCROOT/$DRUPAL_PROJECTS_PATH "$@"
  fi
fi

# php -d xdebug.remote_port=9003 /var/www/html/vendor/bin/phpunit -c /var/www/html/phpunit.xml --testsuite "$@"
